version: '2'

services:
  postgres:
    restart: always
    image: cbihcity/pg
    container_name: pg
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'pass'
    ports:
      - "5432:5432"
  simple-jpa-ap:
    restart: always
    image: cbihcity/simple-jpa-ap
    container_name: simple
    links:
      - postgres
    ports:
      - "8090:8090"